language: node_js
os: linux
node_js:
  - lts/*
script:
  - npm run lint
  - npm run prettier:fix
deploy:
  provider: heroku
  api_key:
    secure: NF6QGW7uhM7NwHBEo2X5PKAqFZEzt2NQflykzHa5FZeZMSAmtgLl8iaOcefi0prCgrqaYrhComlLFE+g0ou2+4jxR/KX3cIWKmaXK/ifuqnDFL1y62HcsUD5d9hyYesXeCsJd3PMV0uvJC7z70pwyB1aD3vICUO0oJ95lMNdQKZyl8w8hQ99eRw1w9tDBqkmu2b2kWsWUNj/KbdKCqXi1rmAjNGREkjcXbsYPym5CWkbtGZ5lXbZ8TDTbMaDmMlGMlYjp9h2z3EMehHGXqKkUo1o0uVkY6uVA5U4se9Fid0lhx1tL/6UWV3lZkWXsC4HyPjxbIL3mbulasPwICb8xiMbCpBukmKRoe3icht0sfqtbXqUpxKx7RVDKVUd9X44GTN6sI0BhnqTOuLtoNv1cpeXg7I/apuHHgjYU47uA3Ulzt0BGsNJHZ4TaFEdJTBsdJD1WDSLh8mmDjkzz2girkpBH4Nx5L7ApxAMxBQAHcCARJDvVyZ0O71frpATkUL9oNCKeu6R/ee54hxnSpz2CSk7w1YYRrDN4b5hCv32EBJe0rZufI5S9aiFAUOgcX2S8Z1Ilf/MFerCo8saP6+wKdN2JYRup8k/85t3rqsC6z043aRg8qmA2CT2K9RsbgGcO8L5fcjMlVyIjaIBZfKJxmBx436PlvX+33eJrX0H0zc=
  on:
    branch: main
branches:
  only:
    - main
